apiVersion: v1
kind: Service
metadata:
  name: eduverse-service
  namespace: eduverse-ns
spec:
  type: NodePort
  selector:
    app: eduverse
  ports:
  - name: backend
    port: 80
    targetPort: 5000
    nodePort: 30007
  - name: frontend
    port: 81
    targetPort: 5173
    nodePort: 30008